#!/usr/bin/env python3

"""
Make up a synthetic Sigsum proof

Given a policy file that uses deterministic secrets (as generated by
rekey-policy.py), this script produces a proof that validates against that
policy.

Free parameters of the proof (like the tree size) can be controlled explicitly
or derived pseudorandomly from a seed. If no seed is given, it is generated
randomly (which makes the execution nondeterministic).
"""

import argparse
import secrets
import sys
import logging

from nacl.signing import SigningKey, VerifyKey

from pathlib import Path

import utils
from utils import sha256, PRNG

RNG: PRNG

def build_parser():
    parser = argparse.ArgumentParser(prog="make-proof")

    parser.add_argument("--seed", type=str)
    parser.add_argument("policy", type=Path)
    parser.add_argument("--log", type=str)
    parser.add_argument("--leaf-key", type=str)
    parser.add_argument("--message-hash", type=str)
    parser.add_argument("--tree-size", type=int)
    parser.add_argument("--leaf-index", type=int)
    parser.add_argument("--cosignature-timestamp", type=int)

    return parser


def read_policy(file: Path) -> tuple[list[str], list[str]]:
    logs = []
    witnesses = []

    policy = file.read_text()
    for line in policy.splitlines():
        if line.startswith('log '):
            _, _, url = line.split()
            logs.append(url)
        elif line.startswith('witness '):
            _, name, _= line.split(maxsplit=2)
            witnesses.append(name)

    return logs, witnesses


def make_leaf(key: SigningKey, message_hash: bytes) -> bytes:
    if len(message_hash) != 32:
        raise ValueError('invalid message hash')

    checksum = sha256(message_hash)
    sig = key.sign(b'sigsum.org/v1/tree-leaf\x00' + checksum).signature

    return checksum + sig + sha256(bytes(key.verify_key))


def format_checkpoint(key: VerifyKey, tree_size: int, root_hash) -> str:
    checkpoint = f'sigsum.org/v1/tree/{sha256(bytes(key)).hex()}\n'
    checkpoint += '%d\n' % tree_size
    checkpoint += utils.b64enc(root_hash) + '\n'

    return checkpoint


def cosign_root(key: SigningKey, timestamp: int, checkpoint: str) -> bytes:
    data = f'cosignature/v1\ntime {timestamp}\n{checkpoint}'
    return key.sign(data.encode()).signature


def make_inclusion_proof(leaf: bytes, leaf_index: int, tree_size: int) -> tuple[list[bytes], bytes]:
    leaf_hash = sha256(b'\x00' + leaf)

    if tree_size == 1:
        return [], leaf_hash

    fn = leaf_index
    sn = tree_size - 1

    r = leaf_hash

    proof = []

    step = 1
    while sn:
        p = step.to_bytes(8, byteorder='little') + b'\x5a'*24
        proof.append(p)

        if (fn&1 != 0) or (fn == sn):
            r = sha256(b'\x01' + p + r)

            if fn&1 == 0:
                while True:
                    fn >>= 1
                    sn >>= 1

                    if (fn&1 != 0) or (fn == 0):
                        break
        else:
            r = sha256(b'\x01' + r + p)

        fn >>= 1
        sn >>= 1
        step += 1

    return proof, r


def generate_proof(
    message_hash: bytes,
    leaf_key: SigningKey, log_key: SigningKey,
    leaf_index: int, tree_size: int,
    witnesses: list[str], cosignature_timestamp: int,
):
    print('version=2')
    print(f'log={sha256(bytes(log_key.verify_key)).hex()}')

    leaf = make_leaf(leaf_key, message_hash)
    inclusion_proof, root_hash = make_inclusion_proof(leaf, leaf_index, tree_size)

    print(f'leaf={leaf[96:].hex()} {leaf[32:96].hex()}')
    print('')
    print(f'size={tree_size}')
    print(f'root_hash={root_hash.hex()}')
    checkpoint = format_checkpoint(log_key.verify_key, tree_size, root_hash)
    root_signature = log_key.sign(checkpoint.encode()).signature
    print(f'signature={root_signature.hex()}')
    for witness_name in witnesses:
        witness_key = SigningKey(utils.derive(witness_name)[0])
        cosignature = cosign_root(witness_key, cosignature_timestamp, checkpoint)
        print(f'cosignature={sha256(bytes(witness_key.verify_key)).hex()} {cosignature_timestamp} {cosignature.hex()}')

    if tree_size > 1:
        print('')
        print(f'leaf_index={leaf_index}')
        for h in inclusion_proof:
            print(f'node_hash={h.hex()}')


def main():
    logging.basicConfig(level=logging.INFO)

    args = build_parser().parse_args()

    if args.seed is not None:
        RNG = PRNG(bytes.fromhex(args.seed))
    else:
        seed = secrets.token_bytes(8)
        logging.info('using random RNG seed: %s', seed.hex())
        RNG = PRNG(seed)

    policy = read_policy(args.policy)
    if args.log is not None:
        log_name = None
        for name in policy[0]:
            if args.log in name:
                log_name = name
                break

        if log_name is None:
            logging.error('no log found for substring %s', log_name)
            sys.exit(1)

    else:
        log_name = policy[0][RNG.get_named_int('log', len(policy[0]))]
        logging.info('selecting log randomly: %s', log_name)

    log_key = SigningKey(utils.derive(log_name)[0])

    if args.leaf_key is not None:
        leaf_key = SigningKey(bytes.fromhex(args.leaf_key))
    else:
        leaf_key = SigningKey(RNG.get_named('leaf-key'))
        logging.info('using random leaf key: private %s / public %s', bytes(leaf_key).hex(), bytes(leaf_key.verify_key).hex())

    if args.message_hash is not None:
        message_hash = bytes.fromhex(args.message_hash)
    else:
        message_hash = RNG.get_named('message-hash')
        logging.info('using random message hash: %s', message_hash.hex())

    if args.tree_size is not None:
        tree_size = args.tree_size
    else:
        tree_size = RNG.get_named_int('tree-size', limit=1<<63)
        logging.info('using random tree size: %d', tree_size)

    if args.leaf_index is not None:
        leaf_index = args.leaf_index
    else:
        leaf_index = tree_size-1 - RNG.get_named_int('leaf-index-offset', limit = tree_size)
        logging.info('using random leaf index: %d', leaf_index)

    if args.cosignature_timestamp is not None:
        cosignature_timestamp = args.cosignature_timestamp
    else:
        cosignature_timestamp = RNG.get_named_int('cosignature-timestamp', limit = 1<<63)
        logging.info('using random cosignature timestamp: %d', cosignature_timestamp)

    if leaf_index >= tree_size:
        logging.error('leaf_index (%d) must be < tree_size (%d)', leaf_index, tree_size)
        sys.exit(1)

    generate_proof(message_hash, leaf_key, log_key, leaf_index, tree_size, policy[1], cosignature_timestamp)


if __name__ == "__main__":
    main()
