#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2025 Florian Larysch <fl@n621.de>
#
# SPDX-License-Identifier: BSD-2-Clause-Patent OR CC0-1.0

"""
Make up a synthetic Sigsum proof

Given a policy file that uses deterministic secrets (as generated by
rekey-policy.py), this script produces a proof that validates against that
policy.

Free parameters of the proof (like the tree size) can be controlled explicitly
or derived pseudorandomly from a seed. If no seed is given, it is generated
randomly (which makes the execution nondeterministic).
"""

import argparse
import secrets
import sys
import logging

from nacl.signing import SigningKey

from pathlib import Path

import test_utils

RNG: test_utils.PRNG

def build_parser():
    parser = argparse.ArgumentParser(prog="make-proof")

    parser.add_argument("--seed", type=str)
    parser.add_argument("policy", type=Path)
    parser.add_argument("--log", type=str)
    parser.add_argument("--leaf-key", type=str)
    parser.add_argument("--message-hash", type=str)
    parser.add_argument("--tree-size", type=int)
    parser.add_argument("--leaf-index", type=int)
    parser.add_argument("--cosignature-timestamp", type=int)

    return parser


def main():
    logging.basicConfig(level=logging.INFO)

    args = build_parser().parse_args()

    if args.seed is not None:
        RNG = test_utils.PRNG(bytes.fromhex(args.seed))
    else:
        seed = secrets.token_bytes(8)
        logging.info('using random RNG seed: %s', seed.hex())
        RNG = test_utils.PRNG(seed)

    policy = test_utils.read_policy(args.policy)
    if args.log is not None:
        log_name = None
        for name in policy[0]:
            if args.log in name:
                log_name = name
                break

        if log_name is None:
            logging.error('no log found for substring %s', log_name)
            sys.exit(1)

    else:
        log_name = policy[0][RNG.get_named_int('log', len(policy[0]))]
        logging.info('selecting log randomly: %s', log_name)

    log_key = test_utils.derive_key(log_name)

    if args.leaf_key is not None:
        leaf_key = SigningKey(bytes.fromhex(args.leaf_key))
    else:
        leaf_key = SigningKey(RNG.get_named('leaf-key'))
        logging.info('using random leaf key: private %s / public %s', bytes(leaf_key).hex(), bytes(leaf_key.verify_key).hex())

    if args.message_hash is not None:
        message_hash = bytes.fromhex(args.message_hash)
    else:
        message_hash = RNG.get_named('message-hash')
        logging.info('using random message hash: %s', message_hash.hex())

    if args.tree_size is not None:
        tree_size = args.tree_size
    else:
        tree_size = RNG.get_named_int('tree-size', limit=1<<63)
        logging.info('using random tree size: %d', tree_size)

    if args.leaf_index is not None:
        leaf_index = args.leaf_index
    else:
        leaf_index = tree_size-1 - RNG.get_named_int('leaf-index-offset', limit = tree_size)
        logging.info('using random leaf index: %d', leaf_index)

    if args.cosignature_timestamp is not None:
        cosignature_timestamp = args.cosignature_timestamp
    else:
        cosignature_timestamp = RNG.get_named_int('cosignature-timestamp', limit = 1<<63)
        logging.info('using random cosignature timestamp: %d', cosignature_timestamp)

    if leaf_index >= tree_size:
        logging.error('leaf_index (%d) must be < tree_size (%d)', leaf_index, tree_size)
        sys.exit(1)

    print(test_utils.generate_proof(message_hash, leaf_key, log_key, leaf_index, tree_size, policy[1], cosignature_timestamp))


if __name__ == "__main__":
    main()
